title: Blog
description: Personal blog
baseurl: "/blog"
url: ""

permalink: /:title/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - scripts/
  - theme/
  - .post-mapping.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
